# Set your plymouth configuration here.
[Daemon]
Theme=archcraft
# add delay to prevent the flicker on systems that boot quickly
ShowDelay=0
# HiDPI display
#DeviceScale=2
# keep the firmware background
#UseFirmwareBackground=true
